-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 22:09:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`League`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`League` (
  `idLeague` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLeague`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participates` (
  `idParticipates` INT NOT NULL AUTO_INCREMENT,
  `idTeam` INT NOT NULL,
  `idLeague` INT NOT NULL,
  PRIMARY KEY (`idParticipates`),
  INDEX `FK_Team_Participates_idx` (`idTeam` ASC) VISIBLE,
  INDEX `FK_League_Participates_idx` (`idLeague` ASC) VISIBLE,
  CONSTRAINT `FK_Team_Participates`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_League_Participates`
    FOREIGN KEY (`idLeague`)
    REFERENCES `mydb`.`League` (`idLeague`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `Forename` VARCHAR(255) NOT NULL,
  `Surname` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `idTeam` INT NOT NULL,
  `Country` VARCHAR(255) NOT NULL,
  `Position` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPlayer`),
  INDEX `FK_Team_Player_idx` (`idTeam` ASC) VISIBLE,
  CONSTRAINT `FK_Team_Player`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fixture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fixture` (
  `idFixture` INT NOT NULL AUTO_INCREMENT,
  `idTeamHome` INT NOT NULL,
  `idTeamAway` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Score` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFixture`),
  INDEX `FK_TeamHome_Fixture_idx` (`idTeamHome` ASC) VISIBLE,
  INDEX `FK_TeamAway_Fixture_idx` (`idTeamAway` ASC) VISIBLE,
  CONSTRAINT `FK_TeamHome_Fixture`
    FOREIGN KEY (`idTeamHome`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TeamAway_Fixture`
    FOREIGN KEY (`idTeamAway`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Forename` VARCHAR(255) NOT NULL,
  `Surename` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(255) NOT NULL,
  `Tokens` INT NOT NULL,
  `Gold` INT NOT NULL,
  `Silver` INT NOT NULL,
  `Bronze` INT NOT NULL,
  `Appearances` INT NOT NULL,
  `Rank` INT NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `FK_Role_User_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `FK_Role_User`
    FOREIGN KEY (`idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idFixture` INT NOT NULL,
  `Text` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `FK_User_Comment_idx` (`idUser` ASC) VISIBLE,
  INDEX `FK_Fixture_Comment_idx` (`idFixture` ASC) VISIBLE,
  CONSTRAINT `FK_User_Comment`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Fixture_Comment`
    FOREIGN KEY (`idFixture`)
    REFERENCES `mydb`.`Fixture` (`idFixture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ArticleType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ArticleType` (
  `idArticleType` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idArticleType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `Image` BLOB NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Value` VARCHAR(255) NOT NULL,
  `idArticleType` INT NOT NULL,
  `Text` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `FK_ArticleType_Article_idx` (`idArticleType` ASC) VISIBLE,
  CONSTRAINT `FK_ArticleType_Article`
    FOREIGN KEY (`idArticleType`)
    REFERENCES `mydb`.`ArticleType` (`idArticleType`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owns` (
  `idOwns` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idArticle` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`idOwns`),
  INDEX `FK_User_Owns_idx` (`idUser` ASC) VISIBLE,
  INDEX `FK_Article_Owns_idx` (`idArticle` ASC) VISIBLE,
  CONSTRAINT `FK_User_Owns`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Article_Owns`
    FOREIGN KEY (`idArticle`)
    REFERENCES `mydb`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ManagerTeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ManagerTeam` (
  `idManagerTeam` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `Offence` INT NOT NULL,
  `Defence` INT NOT NULL,
  `Value` INT NOT NULL,
  `Overall` INT NOT NULL,
  `Rank` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idManagerTeam`),
  INDEX `FK_User_ManagerTeam_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `FK_User_ManagerTeam`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ManagerPlays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ManagerPlays` (
  `idManagerPlays` INT NOT NULL AUTO_INCREMENT,
  `idManagerTeam` INT NOT NULL,
  `idPlayer` INT NOT NULL,
  PRIMARY KEY (`idManagerPlays`),
  INDEX `FK_ManagerTeam_ManagerPlays_idx` (`idManagerTeam` ASC) VISIBLE,
  INDEX `FK_Player_ManagerPlays_idx` (`idPlayer` ASC) VISIBLE,
  CONSTRAINT `FK_ManagerTeam_ManagerPlays`
    FOREIGN KEY (`idManagerTeam`)
    REFERENCES `mydb`.`ManagerTeam` (`idManagerTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Player_ManagerPlays`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Championship` (
  `idChampionship` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idChampionship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChampionshipManagerTeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChampionshipManagerTeam` (
  `idChampionshipManagerTeam` INT NOT NULL AUTO_INCREMENT,
  `idChampionship` INT NOT NULL,
  `idManagerTeam` INT NOT NULL,
  `Rank` INT NOT NULL,
  PRIMARY KEY (`idChampionshipManagerTeam`),
  INDEX `FK_Championship_CMT_idx` (`idChampionship` ASC) VISIBLE,
  INDEX `FK_ManagerTeam_CMT_idx` (`idManagerTeam` ASC) VISIBLE,
  CONSTRAINT `FK_Championship_CMT`
    FOREIGN KEY (`idChampionship`)
    REFERENCES `mydb`.`Championship` (`idChampionship`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ManagerTeam_CMT`
    FOREIGN KEY (`idManagerTeam`)
    REFERENCES `mydb`.`ManagerTeam` (`idManagerTeam`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
