# Generated by Django 4.0.4 on 2022-04-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idarticle', models.AutoField(db_column='idArticle', primary_key=True, serialize=False)),
                ('image', models.TextField(db_column='Image')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('value', models.CharField(db_column='Value', max_length=255)),
                ('text', models.CharField(db_column='Text', max_length=255)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articletype',
            fields=[
                ('idarticletype', models.AutoField(db_column='idArticleType', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'articletype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('idchampionship', models.AutoField(db_column='idChampionship', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'championship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Championshipmanagerteam',
            fields=[
                ('idchampionshipmanagerteam', models.AutoField(db_column='idChampionshipManagerTeam', primary_key=True, serialize=False)),
                ('rank', models.IntegerField(db_column='Rank')),
            ],
            options={
                'db_table': 'championshipmanagerteam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idcomment', models.AutoField(db_column='idComment', primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='Text', max_length=255)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('idfixture', models.AutoField(db_column='idFixture', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('score', models.CharField(db_column='Score', max_length=255)),
            ],
            options={
                'db_table': 'fixture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('idleague', models.AutoField(db_column='idLeague', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('country', models.CharField(db_column='Country', max_length=255)),
            ],
            options={
                'db_table': 'league',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Managerplays',
            fields=[
                ('idmanagerplays', models.AutoField(db_column='idManagerPlays', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'managerplays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Managerteam',
            fields=[
                ('idmanagerteam', models.AutoField(db_column='idManagerTeam', primary_key=True, serialize=False)),
                ('offence', models.IntegerField(db_column='Offence')),
                ('defence', models.IntegerField(db_column='Defence')),
                ('value', models.IntegerField(db_column='Value')),
                ('overall', models.IntegerField(db_column='Overall')),
                ('rank', models.IntegerField(db_column='Rank')),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'managerteam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('idowns', models.AutoField(db_column='idOwns', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(db_column='Amount')),
            ],
            options={
                'db_table': 'owns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participates',
            fields=[
                ('idparticipates', models.AutoField(db_column='idParticipates', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'participates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('idplayer', models.AutoField(db_column='idPlayer', primary_key=True, serialize=False)),
                ('forename', models.CharField(db_column='Forename', max_length=255)),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('country', models.CharField(db_column='Country', max_length=255)),
                ('position', models.CharField(db_column='Position', max_length=255)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.AutoField(db_column='idRole', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('idteam', models.AutoField(db_column='idTeam', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('country', models.CharField(db_column='Country', max_length=255)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('forename', models.CharField(db_column='Forename', max_length=255)),
                ('surename', models.CharField(db_column='Surename', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('tokens', models.IntegerField(db_column='Tokens')),
                ('gold', models.IntegerField(db_column='Gold')),
                ('silver', models.IntegerField(db_column='Silver')),
                ('bronze', models.IntegerField(db_column='Bronze')),
                ('appearances', models.IntegerField(db_column='Appearances')),
                ('rank', models.IntegerField(db_column='Rank')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
