# Generated by Django 4.0.4 on 2022-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idrole',
        ),
        migrations.AlterField(
            model_name='user',
            name='appearances',
            field=models.IntegerField(db_column='Appearances', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bronze',
            field=models.IntegerField(db_column='Bronze', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.IntegerField(db_column='Gold', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(db_column='Rank', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='silver',
            field=models.IntegerField(db_column='Silver', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(db_column='Tokens', default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
