# Generated by Django 4.0.4 on 2022-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(db_column='Age', default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.CharField(db_column='Photo', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.CharField(db_column='Photo', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(db_column='Profile_picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_given',
            field=models.IntegerField(db_column='Tokens_given', default=0),
        ),
    ]
